server:
  port: 9010
spring:
  application:
    name: "webapp"
  profiles:
    active: "dev"

  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    openfeign:

eureka:
  instance:
    preferIpAddress: true

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

