services:

  ccdb:
    container_name: ccdb
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: ccdb
    extends:
      file: common-config.yml
      service: microservice-db-config

networks:
  citycare: